version: '3.3'
services:
  # Main services
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
        - postgres
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
        - api
  celery:
      build:
        context: ./celery
        dockerfile: Dockerfile
      depends_on:
        - redis
        - flower
      volumes:
        - ./celery/app:/app
  # Databases
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD:changethis
      - POSTGRES_USER:root
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  # Others
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  flower:
      image: mher/flower
      ports:
        - '5555:5555'
      depends_on:
        - redis
      environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
      - FLOWER_BASIC_AUTH=root:admin.321&

volumes:
  app-db-data: