name: API
on:
  push:
    paths:
      - 'api/**'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Setup
        run: |
          cd api
          ls -la
          npm ci
      - name: Linter
        working-directory: ./api
        run: npm run lint:ci
      - name: Unit tests
        working-directory: ./api
        run: npm run test