name: API
on:
  push:
    branches:
      - "main"
    paths:
      - 'webapp/**'
jobs:
  webapp-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Setup
        run: | 
          cd api
          npm ci
      - name: Linter
        run: npm run lint:ci