name: WebApp
on:
  push:
    paths:
      - 'webapp/**'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Setup
        working-directory: ./webapp
        run: npm ci
      - name: Linter
        working-directory: ./webapp
        run: npm run lint